### ISSUE TITLE
Corrections mineures

### ISSUE THREAD

**Issue by VinchC** [WildCodeSchool/html-basics-workshop#2]
Bonjour.
Voici des petites modifications à apporter.

Dans la partie 
_"Navbar
Try to reproduce the navbar. Start to create a <nav> tag and add the background color #f76c6c."_

Le code color indiqué est l'ancien sans doute, il convient de le remplacer par le nouveau #a306b6

Dans le footer, il est écrit "2022" et non "2023":)

**Comment by jeanfrancois-morin** [comment]
Bien vu le code couleur ! merci 😉
Pour la date, on est en HTML donc difficile de rendre ça dynamique, on peut changer pour 2023 mais on retrouvera le problème dans 6 mois 😃...
